<a href="https://colab.research.google.com/github/ShauryaDusht/ML/blob/main/ML_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import torch as t

In [4]:
a = t.tensor([1,2,3]) # tensor takes only 1 tensor as input
print(a)
a.ndim # ndim gives the dimension of tensor

tensor([1, 2, 3])


1

In [5]:
s = t.tensor(7)
s.ndim # scalar has 0 ndim

0

In [6]:
aa = t.tensor([[1,2,3],[4,5,6],[7,8,9]])
aa.ndim # there are 2d matrix so 2 is given as answer

2

In [7]:
print(aa.shape)
print(a.shape)


torch.Size([3, 3])
torch.Size([3])


In [8]:
r = t.rand(size=(2,3))
r, r.dtype # dtype gives the data type of tensor

(tensor([[0.0707, 0.5348, 0.9371],
         [0.4186, 0.6166, 0.2227]]),
 torch.float32)

In [9]:
z = t.zeros(size=(3,4))
z, z.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

In [10]:
o = t.zeros(size=(3,4))
o, o.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

In [11]:
range = t.arange(start=1,end=101,step=2) # start,end,step same as python
range

tensor([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35,
        37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67, 69, 71,
        73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [12]:
# create a zero array similar to a tensor
tt = t.zeros_like(input=aa)
tt,aa

(tensor([[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]]),
 tensor([[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]))

In [13]:
# Create a tensor
some_tensor = t.rand(3, 4)

# Find out details about it
print(some_tensor)
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Device tensor is stored on: {some_tensor.device}") # will default to CPU

tensor([[0.7347, 0.1647, 0.7026, 0.4375],
        [0.1901, 0.2310, 0.4856, 0.6705],
        [0.7184, 0.0989, 0.0667, 0.3389]])
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


Arithematic operations

In [14]:
a

tensor([1, 2, 3])

In [15]:
a + 10, a*10, a-10,

(tensor([11, 12, 13]), tensor([10, 20, 30]), tensor([-9, -8, -7]))

In [16]:
# we can use t.add() and t.mul() to perform addition and multiplication
# '*' does element wise multiplication
t.multiply(a,10), t.add(a,10)

(tensor([10, 20, 30]), tensor([11, 12, 13]))

In [17]:
# matrix multiplication
# NxM and MxP matrix can only be multiplied
# otherwise it will throw error
print("Elementwise multiplication: ", a*a)
print("Matrix Multiplication: ", aa.matmul(aa)) # t.mm() can also be used
# matmul function is always fater than conventional for loops to find matrix multiplication

Elementwise multiplication:  tensor([1, 4, 9])
Matrix Multiplication:  tensor([[ 30,  36,  42],
        [ 66,  81,  96],
        [102, 126, 150]])


In [18]:
# Transpose
t.matmul(r,r.T)

tensor([[1.1692, 0.5680],
        [0.5680, 0.6050]])

In [23]:
# Neural networks are full of matrix mul and dot products
# We can also use linear() function to change shape of a input to a desired one
# Since the linear layer starts with a random weights matrix, let's make it reproducible (more on this later)
t.manual_seed(42)
# This uses matrix multiplication
linear = t.nn.Linear(in_features=2, # in_features = matches inner dimension of input
                         out_features=6) # out_features = describes outer value
linear
# linear tensor is like a system with 2 input and 6 output
# or it is a layer in neural network

Linear(in_features=2, out_features=6, bias=True)

In [24]:
print(a)
print(a.min())
print(a.max())
print(a.sum())
print(a.type(t.float32).mean())  # for mean data should be in float32 format

tensor([1, 2, 3])
tensor(1)
tensor(3)
tensor(6)
tensor(2.)


In [27]:
# find index of max and min
print(aa.argmin())
print(aa.argmax())
print(aa)

tensor(0)
tensor(8)
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


In [32]:
# changing datatype of a tensor
# we can reduce computational power using particular datatype
aa_float16 = aa.type(t.float16)
aa_float32 = aa.type(t.float32)
aa_int8 = aa.type(t.int8)
aa_int16 = aa.type(t.int16)
print(aa_float16)
print(aa_float32)
print(aa_int8)
print(aa_int16)

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]], dtype=torch.float16)
tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]], dtype=torch.int8)
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]], dtype=torch.int16)


In [38]:
# Reshaping, Stacking, Squeezing, Unsqueezing
g = t.arange(1,21)
g,g.shape

(tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
         19, 20]),
 torch.Size([20]))

In [43]:
# Reshape add extra dimension
gr = g.reshape(2,2,5)
print(gr, gr.shape)
# view can also be used
gv = g.view(4,5)
print(gv)
# changing the view also changes the original tensor
# both g and gv share the same memory location

tensor([[[ 1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10]],

        [[11, 12, 13, 14, 15],
         [16, 17, 18, 19, 20]]]) torch.Size([2, 2, 5])
tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20]])


In [ ]:
# Stacking