In [47]:
import torch as t

## Basics

In [48]:
a = t.tensor([1,2,3]) # tensor takes only 1 tensor as input
print(a)
a.ndim # ndim gives the dimension of tensor

tensor([1, 2, 3])


1

In [49]:
s = t.tensor(7)
s.ndim # scalar has 0 ndim

0

In [50]:
aa = t.tensor([[1,2,3],[4,5,6],[7,8,9]])
aa.ndim # there are 2d matrix so 2 is given as answer

2

In [51]:
print(aa.shape)
print(a.shape)


torch.Size([3, 3])
torch.Size([3])


In [52]:
r = t.rand(size=(2,3))
r, r.dtype # dtype gives the data type of tensor

(tensor([[0.8854, 0.5739, 0.2666],
         [0.6274, 0.2696, 0.4414]]),
 torch.float32)

In [53]:
z = t.zeros(size=(3,4))
z, z.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

In [54]:
o = t.zeros(size=(3,4))
o, o.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

In [55]:
range = t.arange(start=1,end=101,step=2) # start,end,step same as python
range

tensor([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35,
        37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67, 69, 71,
        73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [56]:
# create a zero array similar to a tensor
tt = t.zeros_like(input=aa)
tt,aa

(tensor([[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]]),
 tensor([[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]))

In [57]:
# Create a tensor
some_tensor = t.rand(3, 4)

# Find out details about it
print(some_tensor)
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Device tensor is stored on: {some_tensor.device}") # will default to CPU

tensor([[0.2969, 0.8317, 0.1053, 0.2695],
        [0.3588, 0.1994, 0.5472, 0.0062],
        [0.9516, 0.0753, 0.8860, 0.5832]])
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


## Arithematic operations

In [58]:
a

tensor([1, 2, 3])

In [59]:
a + 10, a*10, a-10,

(tensor([11, 12, 13]), tensor([10, 20, 30]), tensor([-9, -8, -7]))

In [60]:
# we can use t.add() and t.mul() to perform addition and multiplication
# '*' does element wise multiplication
t.multiply(a,10), t.add(a,10)

(tensor([10, 20, 30]), tensor([11, 12, 13]))

In [61]:
# matrix multiplication
# NxM and MxP matrix can only be multiplied
# otherwise it will throw error
print("Elementwise multiplication: ", a*a)
print("Matrix Multiplication: ", aa.matmul(aa)) # t.mm() can also be used
# matmul function is always fater than conventional for loops to find matrix multiplication

Elementwise multiplication:  tensor([1, 4, 9])
Matrix Multiplication:  tensor([[ 30,  36,  42],
        [ 66,  81,  96],
        [102, 126, 150]])


Transpose

In [62]:
t.matmul(r,r.T)

tensor([[1.1844, 0.8280],
        [0.8280, 0.6612]])

In [63]:
# Neural networks are full of matrix mul and dot products
# We can also use linear() function to change shape of a input to a desired one
# Since the linear layer starts with a random weights matrix, let's make it reproducible (more on this later)
t.manual_seed(42)
# This uses matrix multiplication
linear = t.nn.Linear(in_features=2, # in_features = matches inner dimension of input
                         out_features=6) # out_features = describes outer value
linear
# linear tensor is like a system with 2 input and 6 output
# or it is a layer in neural network

Linear(in_features=2, out_features=6, bias=True)

In [64]:
print(a)
print(a.min())
print(a.max())
print(a.sum())
print(a.type(t.float32).mean())  # for mean data should be in float32 format

tensor([1, 2, 3])
tensor(1)
tensor(3)
tensor(6)
tensor(2.)


In [65]:
# find index of max and min
print(aa.argmin())
print(aa.argmax())
print(aa)

tensor(0)
tensor(8)
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


In [66]:
# changing datatype of a tensor
# we can reduce computational power using particular datatype
aa_float16 = aa.type(t.float16)
aa_float32 = aa.type(t.float32)
aa_int8 = aa.type(t.int8)
aa_int16 = aa.type(t.int16)
print(aa_float16)
print(aa_float32)
print(aa_int8)
print(aa_int16)

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]], dtype=torch.float16)
tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]], dtype=torch.int8)
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]], dtype=torch.int16)


## Reshaping, Stacking, Squeezing, Unsqueezing

In [67]:
# Reshaping : change arrangement of tensor
g = t.arange(1,21)
g,g.shape

(tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
         19, 20]),
 torch.Size([20]))

In [68]:
# Reshape : add extra dimension
gr = g.reshape(2,2,5)
print(gr, gr.shape)
# view can also be used
gv = g.view(4,5)
print(gv)
# changing the view also changes the original tensor
# both g and gv share the same memory location

tensor([[[ 1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10]],

        [[11, 12, 13, 14, 15],
         [16, 17, 18, 19, 20]]]) torch.Size([2, 2, 5])
tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20]])


In [69]:
# Stacking : stacks new tensor on top of itself
g_stacked = t.stack([g, g, g, g],dim = 0)
g_stacked

tensor([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
         19, 20],
        [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
         19, 20],
        [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
         19, 20],
        [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
         19, 20]])

In [70]:
# Squeezing : 1 dimension is removed
x = t.arange(1., 8.)
x_reshaped = x.reshape(1, 7)

print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimension from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[1., 2., 3., 4., 5., 6., 7.]])
Previous shape: torch.Size([1, 7])

New tensor: tensor([1., 2., 3., 4., 5., 6., 7.])
New shape: torch.Size([7])


In [71]:
# Unsqueezing : opposite of squeezing
print(f"Previous tensor: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

## Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous tensor: tensor([1., 2., 3., 4., 5., 6., 7.])
Previous shape: torch.Size([7])

New tensor: tensor([[1., 2., 3., 4., 5., 6., 7.]])
New shape: torch.Size([1, 7])


In [72]:
# Permute : change the tensor's axes values to desired ones
x_original = t.rand(size=(224, 224, 3))

# Permute the original tensor to rearrange the axis order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")
## permute returns a view ( share memory with same data as original)

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


## Indexing


In [73]:
x = t.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [74]:
print(f"First square bracket:\n{x[0]}")
print(f"Second square bracket: {x[0][0]}")
print(f"Third square bracket: {x[0][0][0]}")

First square bracket:
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Second square bracket: tensor([1, 2, 3])
Third square bracket: 1


In [75]:
print(x[:, 0])
print(x[:,:,1])
print(x[:,1,1])
print(x[0,0,:])

tensor([[1, 2, 3]])
tensor([[2, 5, 8]])
tensor([5])
tensor([1, 2, 3])


## PyTorch and NumPy#

In [76]:
import torch
import numpy as np
a = np.arange(1,8)
t = torch.from_numpy(a) # from numpy array to pytorch tensor
a, t

(array([1, 2, 3, 4, 5, 6, 7]), tensor([1, 2, 3, 4, 5, 6, 7]))

In [77]:
t = torch.ones(7)
n = t.numpy() # from pytorch tensor to numpy array
t, n

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducibility

In [78]:
a = torch.rand(4,4)
b = torch.rand(4,4)
print(a)
print(b)
a == b
# each time a and b will have different values
# sometime that can be equal as we are using rand function

tensor([[0.8016, 0.3649, 0.6286, 0.9663],
        [0.7687, 0.4566, 0.5745, 0.9200],
        [0.3230, 0.8613, 0.0919, 0.3102],
        [0.9536, 0.6002, 0.0351, 0.6826]])
tensor([[0.3743, 0.5220, 0.1336, 0.9666],
        [0.9754, 0.8474, 0.8988, 0.1105],
        [0.4563, 0.9719, 0.3968, 0.1496],
        [0.4743, 0.9973, 0.4436, 0.9726]])


tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [79]:
## SEEDING


In [80]:
random_seed = 42
torch.manual_seed(seed=random_seed)
r = torch.rand(4,4)

rr = torch.rand(4,4)
print(r)
print(rr)
r == rr

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936],
        [0.8694, 0.5677, 0.7411, 0.4294]])
tensor([[0.8854, 0.5739, 0.2666, 0.6274],
        [0.2696, 0.4414, 0.2969, 0.8317],
        [0.1053, 0.2695, 0.3588, 0.1994],
        [0.5472, 0.0062, 0.9516, 0.0753]])


tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [81]:
random_seed = 42
torch.manual_seed(seed=random_seed)
r = torch.rand(4,4)

torch.manual_seed(seed=random_seed)
rr = torch.rand(4,4)
print(r)
print(rr)
r == rr

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936],
        [0.8694, 0.5677, 0.7411, 0.4294]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936],
        [0.8694, 0.5677, 0.7411, 0.4294]])


tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

## **Usage of GPUs**

In [82]:
!nvidia-smi
# function to check if we have access to Nvidia GPU

Fri Mar  8 09:10:38 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   77C    P0              34W /  70W |    105MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [83]:
import torch
torch.cuda.is_available()
# function to check if GPU using cuda

True

In [84]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

Putting tensors on GPU

In [85]:
tensor = torch.tensor([1, 2, 3])

# Tensor not on GPU
print(tensor, tensor.device)

# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3]) cpu


tensor([1, 2, 3], device='cuda:0')

Moving tensors back to CPU

In [86]:
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

In [87]:
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

## Exercises

In [88]:
import torch as t
import numpy as np

In [89]:
# Q2
